### PR TITLE
Company slug no longer required for tags.

### PR DESCRIPTION
**Pull request by joshuajonah**
…Now it will choose the first company by default. Just makes the tags cleaner when only using one company.

### CODE REVIEW

**Comment by joshuajonah** [comment]
I also fixed an attribute error in `utils.getnow()`.

**Comment by philippeowagner** [comment]
Thanks @joshuajonah for your PR.
These are really valuable improvements on the code base.
Due to backwards incompatibility to the current version you owe us some documentation for your changes ;-)
With other words: I have no problem to merge this, break backwards compatibility and incrementing the version number accordingly but it must be clear what has to be changed to get it work (again). 
Would you mind to enhance your PR? 
Thanks.

**Comment by joshuajonah** [comment]
@philippeowagner I added more documentation showing how it used to be done as well as the new way.

**Comment by philippeowagner** [comment]
That's great @joshuajonah ! :+1: Thanks for your contribution. Will merge it now, double-check it later and release a new version on PyPI.

**Pull request merged**
